version: "4.20"

services:
    server:
        container_name: heldent_server
        build:
            context: ./server
            dockerfile: Dockerfile.server
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        env_file:
            - .env
        environment:
            - DB_HOST=database
        links:
            - client
            - database

    client:
        container_name: heldent_client
        build:
            context: ./frontend
            dockerfile: Dockerfile.client
        ports:
            - 3000:3000

    database:
        container_name: heldent_database
        image: postgres
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
