version: "3.8"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "8080:8080"
        links:
            # - client
            - database
            - test

    # client:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.client

    database:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
